# Archivo: docker-compose.prod.yml
#version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000" 

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    # restart: always
    env_file: ./apps/api/.env.prod
    depends_on:
      - db
    ports:
      - "127.0.0.1:3001:3001"

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./apps/api/.env.prod

volumes:
  postgres_data:
    name: oneto_postgres_data