# Archivo: .github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # Cambiado a npm
          
      - name: Install dependencies
        run: npm ci # 'ci' es más rápido y seguro para CI/CD que 'install'
        
      - name: Linting
        run: npm run lint --if-present # '--if-present' evita errores si el script no existe aún
        
      # Por ahora no tenemos tests, pero aquí irían
      # - name: Run tests
      #   run: npm test --if-present